apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "czepiec-site.fullname" . }}
spec:
  default:
    config:
      type: HTTP
  targetRef:
    group: ""
    kind: Service
    name: {{ include "czepiec-site.fullname" . }}-http
